### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by mxmilkiib** [dan-german/blocks#1]
Hello! I was wondering if Linux support might be a possibility some day? Thanks!

**Comment by dan-german** [comment]
Definitely! but I don't have a Linux machine currently. 
Setting up a GitHub action for it should be straightforward though, so If anyone wants to help with that, feel free [DM'ing me on discord!](https://discord.gg/MjkFj859vW)!

**Comment by dan-german** [comment]
There's Linux support now thanks to @AlexXandreE!

**Comment by Niiisse** [comment]
How does one get this going on Linux? There's only Windows and MacOS download buttons on the website.. Forgive me if i'm being dumb

**Comment by dan-german** [comment]
@Niiisse Go to `Actions` and click the latest workflow run that has "Build Linux" written underneath. 
Here's the latest one: https://github.com/dan-german/blocks/actions/runs/6634361473 (Valid for 30 days)
I've opened an issue to integrate s3 uploads to the build workflows, i'll add a Linux button once that's done :)

**Comment by Niiisse** [comment]
Thank you so much! All the best to you and your wonderful project :)

**Comment by RustoMCSpit** [comment]
> i'll add a Linux button once that's done :)

is it? not on websiote
