### ISSUE TITLE
Segmentation fault with Linux standalone version

### ISSUE THREAD

**Issue by Purfakt** [dan-german/blocks#29]
When I try to run the linux standalone version (downloaded from the website) I instantly get a segmentation fault.

```
$ chmod + x blocks_linux/Standalone/blocks
$ ./blocks_linux/Standalone/blocks
[1]    53837 segmentation fault (core dumped)  ./blocks_linux/Standalone/blocks
```

**Comment by oiwn** [comment]
Got segfault on OSX standalone. The idea is great btw, but there is much to do!

**Comment by dan-german** [comment]
> Got segfault on OSX standalone while doing kick drum patch. The idea is great btw, but there is much to do!

osx version? can you elaborate on how the segault reproduces? there are a lot of ways to patch a drum kick.

**Comment by oiwn** [comment]
> > Got segfault on OSX standalone while doing kick drum patch. The idea is great btw, but there is much to do!
> 
> osx version? can you elaborate on how the segault reproduces? there are a lot of ways to patch a drum kick.

14.2.1 Sonoma I'll try to play with plugin and send proper report if something crash.
